
--IMPRESORAS
SELECT TOP 500 * FROM [020BDCOMUN].DBO.PRINTER 

--CABECERA DE ARTICULO-IMPRESORA
SELECT TOP 500 * FROM [020BDCOMUN].DBO.PRINTER_MAEART_CAB

--DETALLE DE ARTICULO-IMPRESORA
SELECT TOP 500 * FROM [020BDCOMUN].DBO.PRINTER_MAEART_DET
